### ISSUE TITLE
Upgrade to SDL 2.0.10

### ISSUE THREAD

**Issue by weitjong** [urho3d/Urho3D#2324]

**Comment by rokups** [comment]
Current SDL version no longer works with latest emscripten because `EMSCRIPTEN_JoystickInit` is missing `emscripten_sample_gamepad_data()` call and `Pointer_stringify()` was removed in favor of `UTF8ToString()`.

**Comment by weitjong** [comment]
This is a known issue. Use the same Emscripten version as our CI build for now if you want to do Web build.

**Comment by UNDEFINED-BEHAVIOR** [comment]
```EMSCRIPTEN_JoystickInit ```

Simply bumping to vanilla 2.0.8 might not even be enough
https://hg.libsdl.org/SDL/rev/fc8ab202b5a8
This patch appears on 2.0.9

Be ware that 2.0.9 introduce this bug.
https://discourse.libsdl.org/t/sdl2-lag-with-sdl-getticks/25538

Did tried merging locally, no problem with desktop build tho.

**Comment by weitjong** [comment]
A lot has changed since 2.0.9. I think we should skip 2.0.8 and 2.0.9, jump to the current SDL master instead.

**Comment by weitjong** [comment]
It looks like the upstream SDL is preparing to release 2.0.10 already. Fortunately, this time we are not far behind. See #2447. The integration work for Android build is already started. It is more work to make the new SDL work for our Android build than the Web build.

**Comment by weitjong** [comment]
Got the Android build working and the samples running on an AVD. Still not happy though as I am forced to bump the API level to 26 to get it built with the latest upstream SDL changes for Audio and Game-Controller. And since I stuck with my old Galaxy Tab 3 which only has API level 17, I could not verify the work on my Tab.

**Comment by weitjong** [comment]
Good news, the build failure was really just due to `lint` task complaining about higher API call than current min level setting, which can be easily suppressed without actually bumping the min API level that high. However, it still means I could not test the game controller thingy on my old Galaxy Tab 3 even after I fix this issue.

**Comment by weitjong** [comment]
Got the APK running on my Galaxy Tab 3. Should be able to push what I have tomorrow after further clean up and testing. Will also try to buy a USB-on-the-go dongle to see whether I could connect my new PS4 controller using USB instead of Bluetooth.

**Comment by weitjong** [comment]
Didn't got time to test but I just push what I have now after cleaning up as promise.

**Comment by weitjong** [comment]
I need a help from VS user to fix the build error using SHARED lib type. I don't want to merge the dev branch into master later with known CI build failure.

**Comment by weitjong** [comment]
All CI build failures have been fixed, except those on Appveyor.

**Comment by 1vanK** [comment]
no ideas

**Comment by UNDEFINED-BEHAVIOR** [comment]
Adding (debug)
vcruntimed.lib
ucrtd.lib
msvcrtd.lib
msvcprtd.lib
msvcurtd.lib
msvcmrtd.lib
oldnames.lib
fixes majority of unresolved links but didn't fix it all the way.
Still no idea about root cause.

**Comment by weitjong** [comment]
Thanks for the feedback. The CI uses Release build config.

**Comment by 1vanK** [comment]
I founded it in old SDL.c

// Urho3D: removed offending _DllMainCRTStartup function which interfered with CRT initialization
// when building as a shared library

**Comment by weitjong** [comment]
Thanks for lead. I removed the our local fix because I saw upstream SDL has already added a guard (SDL_STATIC_LIB). However, I forget to actually verify under which condition the guard is being set. In fact it was not set at all by upstream. I have rectified that in SDL's CMakeLists.txt in my fork and currently being CI build tested.

**Comment by UNDEFINED-BEHAVIOR** [comment]
Should this be considered stable enough yet?

**Comment by weitjong** [comment]
No. There are still bugs from the upstream implementation.

**Comment by weitjong** [comment]
I guess everyone needs to move on.

The upstream dev seems still fixing bugs for 2.0.10 release and it could take a while. I have revised my subtree merging strategy a little bit, so I can keep merging *incrementally* now without creating too many noise in the commit history. With that I can merge my work so far on my master branch directly, and move on.
