### ISSUE TITLE
2D Raycast collision filtering not work properly

### ISSUE THREAD

**Issue by Yatsomi** [urho3d/Urho3D#2404]
Hi, im using [RayCastSingle()](https://urho3d.github.io/documentation/1.7/class_urho3_d_1_1_physics_world2_d.html#a941235284b5d5ef127a24e0b4abebbdc) in PhysicsWorld2D.cpp, but i have problem with collision filtering, here is my code:

define categories:
>enum GAMELAYERS : const unsigned {
		None = 0,
		Character = 0x0002	,
		Platforms = 0x0004,
	};
>
set character category bits:
>boxCollider_ = GetNode()->CreateComponent<CollisionBox2D>();
boxCollider_->SetCategoryBits(GAMELAYERS::Character);
rigidbody_ = GetNode()->CreateComponent<RigidBody2D>();
>
and raycast:
>physicsWorld_->RaycastSingle(results, startPos, endPos, GAMELAYERS::Platforms);
>
i send platform bits as raycast collisionmask, but it still hit my character. i dont get it.
box2D collision filtering use this method:
>uint16 catA = fixtureA.filter.categoryBits;
uint16 maskA = fixtureA.filter.maskBits;
uint16 catB = fixtureB.filter.categoryBits;
uint16 maskB = fixtureB.filter.maskBits;
if ((catA & maskB) != 0 && (catB & maskA) != 0)
{
// fixtures can collide
}
>

0x0002 & 0x0004 == 0
whats the problem?

**Comment by Modanung** [comment]
To quote Sinoid from [this](https://discourse.urho3d.io/t/raycast-collision-filtering-problem/4735) topic:
> It’s a bug.
>
> CollisionShape2D::CreateFixture() needs to set the filter data on the fixture, it currently doesn’t. So you can only set those category/mask bits if you follow the sequence of Create Rigidbody -> Create shape -> setup shapes size and physical traits -> set category/mask bits

**Comment by JSandusky** [comment]
I'm investigating, there's some weird behaviour here. I don't want to talk about it further until looking at it deeper tomorrow. I think Urho3D side that everything is done correctly as the box2d API intends though.

**Comment by JSandusky** [comment]
I could not reproduce on my end with the latest master:

here's my sloppy repro case in 27_Urho2DPhysics.as: https://gist.github.com/JSandusky/37c12758fdf4dcbfbc3faa67e6ab5762

No matter how I fiddled things around the category/mask always appears to work.

**Comment by LeithKetchell** [comment]
@Yatsomi (OP), did you download Urho3D from the website, or from the git development branch?
@Admins, Can we confirm this issue is resolved, and close it?

@Everyone, We have conflicting reports, can someone confirm whether the last commit to 2D physics was before or after the date of the original post? And it would be nice if we knew what operating system each was using at the time they posted, just to be sure we covered the bases.

**Comment by JSandusky** [comment]
**Note:** My initial confusion with `weird behaviour` comment was a misunderstanding of how the flags/mask were working as well as some minor glitches in what I was doing to check it. 

OP's issue could just be the same initial confusion I had (though that was weeks ago and I can't recall what the confusion was).

**Comment by Yatsomi** [comment]
@LeithKetchell Sorry for the delayed response. Working with latest commit on git branch and the issue is still there. The problem is [RaycastSingle](https://urho3d.github.io/documentation/1.7/class_urho3_d_1_1_physics_world2_d.html#a941235284b5d5ef127a24e0b4abebbdc) use Maskbits to produce results instead of their Category bits! 
here is an example:

`enum LAYERS: const unsigned {
None = 0,
Player = 0x0002 ,
Platforms = 0x0004,
};`

`playerCollider->SetCategoryBits(LAYERS::Player); `
`playerCollider->SetMaskBits(LAYERS::Platforms);`
`physicsWorld2D->RaycastSingle(result, startPoint, endPoint, LAYERS::Platforms);`

Guess what, raycast will hit the playerCollider!

**Comment by Yatsomi** [comment]
> 
> 
> I could not reproduce on my end with the latest master:
> 
> here's my sloppy repro case in 27_Urho2DPhysics.as: https://gist.github.com/JSandusky/37c12758fdf4dcbfbc3faa67e6ab5762
> 
> No matter how I fiddled things around the category/mask always appears to work.

@JSandusky Hey bro. thanks for investigations and sorry for delayed answer. I saw your repro case. The thing is there is no issue in rigidbody collision tests like you did with balls and boxes. The problem appears when using [RaycastSingle](https://urho3d.github.io/documentation/1.7/class_urho3_d_1_1_physics_world2_d.html#a941235284b5d5ef127a24e0b4abebbdc).
