### ISSUE TITLE
UnsubscribeFromEvent() inoperant in lua

### ISSUE THREAD

**Issue by Mike3D** [urho3d/Urho3D#643]
Unsubscribing from events in lua no longer works.

Simple lua script to replicate:
```lua
function Start()
	CreateButton()
	input.mouseVisible = true
end

function CreateButton()
    button = ui.root:CreateChild("Button")
    button:SetSize(200, 100)
    button:SetAlignment(HA_CENTER, VA_CENTER)
    SubscribeToEvent(button, "HoverBegin", "HandleHoverBegin")
    SubscribeToEvent(button, "Released", "HandleClicked")
end

function HandleHoverBegin(eventType, eventData)
	UnsubscribeFromEvent("HoverBegin")
	UnsubscribeFromEvent("HoverBegin", "HandleHoverBegin")
	print("Hover")
end

function HandleClicked(eventType, eventData)
	UnsubscribeFromEvent("Released")
	UnsubscribeFromEvent("Released", "HandleClicked")
	print("Click")
end
```

Whatever method is used to unsubscribe, button continues to send "HoverBegin" and "Released" events.
This issue is lua specific, it works fine in AngelScript.

**Comment by cadaver** [comment]
Your button variable is local, so it doesn't exist in the other functions.

However, the implementation in LuaScript seems to be against usual Urho convention, where calling UnsubscribeFromEvent() with just the event name doesn't unsubscribe from a sender's event (it should). I also observed a crash when calling just UnsubscribeFromEvents(sender).  It would also be likely there are similar bugs in LuaScriptInstance. 

@aster2013 Can you look into these?

**Comment by aster2013** [comment]
Hi, I will look it. thanks.

**Comment by aster2013** [comment]
Fixed

**Comment by Mike3D** [comment]
Aster, many thanks for fixes and overall improvements.
However UnsubscribeFromEvent(eventName) and UnsubscribeFromEvent(eventName, functionOrFunctionName) still don't work for me with the updated script above. I've rebuilt Urho from scratch to ensure I didn't miss something.

**Comment by aster2013** [comment]
I think a bit excessive, I will simplify it.

**Comment by Mike3D** [comment]
Amazing! It works perfectly and has fixed many weird issues like jerky/unpredictable behaviors, lags, random segfaults, ... This one is a big step forward, thanks a lot Aster :heart_eyes:

**Comment by celeron55** [comment]
Wait what? After b6e413e49d1bda944be9da6b31173f3ff9640d46 you can subscribe many callback functions but you can only remove all of them at once?

That is a gross oversimplification because now I need to implement this exact kind of function-level event router myself. Are you sure this is what you intended to do @aster2013?
